### ISSUE TITLE
dtype changes after `most_common` 

### ISSUE THREAD

**Issue by SarahAlidoost** [xarray-contrib/xarray-regrid#52]
It seems that `da.regrid.most_common(...)` changes the `dtype` of da from `uint8` to `float32`. Is this change needed? I tested this issue using [demo notebook](https://github.com/xarray-contrib/xarray-regrid/blob/main/docs/notebooks/demos/demo_most_common.ipynb), just inspect `dtype` before and after regrid.

**Comment by BSchilperoort** [comment]
Hi Sarah, thanks for raising this issue. This is not the intended behavior.

It turns out there are two problems:

1. When restoring the input data's properties (attrs etc.), we use [`.where`](https://github.com/xarray-contrib/xarray-regrid/blob/0bd64aa471f4b8d4e643a4aacfe36dffbfe9e8ad/src/xarray_regrid/methods/_shared.py#L59-L62) which will cast data to a floating point number so NaN can be used.
2. I forgot to expose the `fill_value` kwarg to `regrid.most_common`, so no fill value can be passed by the user.
